# Generated by Django 4.0.5 on 2022-06-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
